# Generated by Django 4.2.1 on 2023-06-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_alter_agenda_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data',
            field=models.DateField(),
        ),
    ]
