# Generated by Django 4.2.1 on 2023-06-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('datanasc', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=20)),
                ('num', models.CharField(max_length=20)),
                ('complemento', models.CharField(max_length=100)),
            ],
        ),
    ]
