# Generated by Django 4.2.1 on 2023-06-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_consulta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
