# Generated by Django 4.1.7 on 2023-06-08 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='datanasc',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='datanasc',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
