# Generated by Django 4.1.7 on 2023-06-09 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_medico_datanasc_paciente_datanasc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_paciente', models.CharField(max_length=100)),
                ('nome_medico', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('horario', models.CharField(max_length=20)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.paciente')),
                ('crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('horario', models.CharField(max_length=20)),
                ('crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.medico')),
            ],
        ),
    ]
