# Generated by Django 4.1.7 on 2023-06-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_remove_medico_id_remove_paciente_id_alter_medico_crm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='datanasc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
