# Generated by Django 4.1.7 on 2023-06-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_medico_datanasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='datanasc',
            field=models.DateField(),
        ),
    ]
