# Generated by Django 4.1.7 on 2023-06-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_alter_medico_datanasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='medico',
            name='datanasc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='datanasc',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
