# Generated by Django 4.2.1 on 2023-06-12 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_alter_agenda_data_alter_consulta_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='especialidade',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
