# Generated by Django 4.2.1 on 2023-06-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_consulta_especialidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='crm',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='crm',
        ),
        migrations.DeleteModel(
            name='Especialidade',
        ),
        migrations.DeleteModel(
            name='Agenda',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
